Vagrant.configure(2) do |config|
  config.vm.box = "winserver2016"
   config.vm.network "forwarded_port", guest: 5985, host: 5985
   config.vm.network "forwarded_port", guest: 3389, host: 3389

   config.vm.provider "virtualbox" do |vb|
     vb.gui = true
   end
end
